# matrix calcus

In [1]:
import torch

In [2]:
X = torch.tensor([[2,6,3],[-4,1,5],[8,6,5]],dtype=torch.float32,requires_grad=True)
X

tensor([[ 2.,  6.,  3.],
        [-4.,  1.,  5.],
        [ 8.,  6.,  5.]], requires_grad=True)

In [3]:
f_x = X**2
f_x

tensor([[ 4., 36.,  9.],
        [16.,  1., 25.],
        [64., 36., 25.]], grad_fn=<PowBackward0>)

In [4]:
d_x = 0.001 * torch.rand(3,3)
d_x

tensor([[4.8932e-04, 1.2945e-04, 6.5734e-04],
        [4.0080e-04, 7.0925e-04, 9.5551e-04],
        [4.3107e-04, 7.3491e-04, 2.2049e-05]])

In [5]:
df = X*d_x + d_x *X
df

tensor([[ 0.0020,  0.0016,  0.0039],
        [-0.0032,  0.0014,  0.0096],
        [ 0.0069,  0.0088,  0.0002]], grad_fn=<AddBackward0>)

In [6]:
num_cal =(X + d_x)**2 - X**2
num_cal

tensor([[ 0.0020,  0.0016,  0.0039],
        [-0.0032,  0.0014,  0.0096],
        [ 0.0069,  0.0088,  0.0002]], grad_fn=<SubBackward0>)

In [7]:
df.allclose(num_cal,rtol=1e-2)

True

In [8]:
f_x.backward(d_x)

In [10]:
backward_cal = X.grad
backward_cal

tensor([[ 0.0020,  0.0016,  0.0039],
        [-0.0032,  0.0014,  0.0096],
        [ 0.0069,  0.0088,  0.0002]])

In [11]:
df.allclose(backward_cal)

True

In [13]:
df.allclose(num_cal,rtol=1e-2)

True